DROP SEQUENCE RETIRE_USERS_SEQ;
CREATE SEQUENCE RETIRE_USERS_SEQ NOCACHE;

DROP TABLE RETIRE_USERS;
CREATE TABLE RETIRE_USERS (
	RETIRE_NO	NUMBER	NOT NULL,
	JOIN_DATE	DATE	NULL,
	RETIRE_DATE	DATE	NULL,
	ID	VARCHAR2(30 BYTE)	NULL
);

ALTER TABLE RETIRE_USERS ADD CONSTRAINT PK_RETIRE_USERS PRIMARY KEY (
	RETIRE_NO
);