--시퀀스 삭제
DROP SEQUENCE BBS_SEQ;
DROP SEQUENCE ACCESS_LOG_SEQ;
DROP SEQUENCE GALLERY_SEQ;
DROP SEQUENCE TBL_LIKE_SEQ;
DROP SEQUENCE TBL_COMMENT_SEQ;
DROP SEQUENCE RETIRE_USERS_SEQ;
DROP SEQUENCE SLEEP_USERS_SEQ;
DROP SEQUENCE ATTACH_SEQ;
DROP SEQUENCE UPLOAD_SEQ;
DROP SEQUENCE BLOG_SEQ;
DROP SEQUENCE COMMENTS_SEQ;
DROP SEQUENCE USERS_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE BBS_SEQ NOCACHE;
CREATE SEQUENCE ACCESS_LOG_SEQ NOCACHE;
CREATE SEQUENCE GALLERY_SEQ NOCACHE;
CREATE SEQUENCE TBL_LIKE_SEQ NOCACHE;
CREATE SEQUENCE TBL_COMMENT_SEQ NOCACHE;
CREATE SEQUENCE RETIRE_USERS_SEQ NOCACHE;
CREATE SEQUENCE SLEEP_USERS_SEQ NOCACHE;
CREATE SEQUENCE ATTACH_SEQ NOCACHE;
CREATE SEQUENCE UPLOAD_SEQ NOCACHE;
CREATE SEQUENCE BLOG_SEQ NOCACHE;
CREATE SEQUENCE COMMENTS_SEQ NOCACHE;
CREATE SEQUENCE USERS_SEQ NOCACHE;

-- 테이블 삭제
DROP TABLE TBL_COMMENT;
DROP TABLE TBL_LIKE;
DROP TABLE SUMMERNOTE_IMAGE;
DROP TABLE GALLERY;
DROP TABLE ATTACH CASCADE CONSTRAINTS;
DROP TABLE UPLOAD CASCADE CONSTRAINTS;
DROP TABLE SLEEP_USERS;
DROP TABLE RETIRE_USERS;
DROP TABLE BBS;
DROP TABLE ACCESS_LOG;
DROP TABLE USERS;

-- 테이블 생성

-- 유저
CREATE TABLE USERS (
	USER_NO	                NUMBER	            NOT NULL,
	ID	                    VARCHAR2(45 BYTE)	UNIQUE NOT NULL,
	PW	                    VARCHAR2(64 BYTE)	NOT NULL,
	NAME	                VARCHAR2(50 BYTE)	NOT NULL,
	GENDER	                VARCHAR2(2 BYTE)    NOT NULL,
	EMAIL	                VARCHAR2(50 BYTE)	NOT NULL,
	MOBILE	                VARCHAR2(11 BYTE)	NOT NULL,
	BIRTHYEAR	            VARCHAR2(4 BYTE)	NOT NULL,
	BIRTHDAY	                VARCHAR2(4 BYTE)	NOT NULL,
	POSTCODE                	VARCHAR2(5 BYTE)	NULL,
	ROAD_ADDRESS	            VARCHAR2(100 BYTE)	NULL,
	JIBUN_ADDRESS	        VARCHAR2(100 BYTE)	NULL,
	DETAIL_ADDRESS	        VARCHAR2(100 BYTE)	NULL,
	EXTRA_ADDRESS	        VARCHAR2(100 BYTE)	NULL,
	AGREE_CODE	            NUMBER	            NOT NULL,
	SNS_TYPE	                VARCHAR2(10 BYTE)	NULL,
	JOIN_DATE	            DATE	            NOT NULL,
	PW_MODIFY_DATE	        DATE	            NULL,
	INFO_MODIFY_DATE        	DATE	            NULL,
	SESSION_ID	            VARCHAR2(32 BYTE)	NULL,
	SESSION_LIMIT_DATE      	DATE	            NULL,
	POINT	                NUMBER	            NULL
);

--로그


CREATE TABLE ACCESS_LOG (
    ID	VARCHAR2(45 BYTE)	NOT NULL UNIQUE,
	ACCESS_LOG_NO	NUMBER	NOT NULL,
	LAST_LOGIN_DATE	DATE	NULL
);



-- 자유게시판
CREATE TABLE BBS (
    BBS_NO NUMBER NOT NULL,
    ID VARCHAR2(45 BYTE) NOT NULL,
    BBS_TITLE  VARCHAR2(1000 BYTE) NOT NULL, 
    CREATE_DATE DATE NOT NULL,
    STATE  NUMBER(1) NOT NULL,  
    DEPTH  NUMBER(2) NOT NULL,  
    GROUP_NO NUMBER NOT NULL, 
    GROUP_ORDER NUMBER NOT NULL,  
    CONTENT VARCHAR2(4000 BYTE) NOT NULL,
    BBS_LAST_MODIFY_DATE DATE NOT NULL,
    IP VARCHAR2(30 BYTE) NOT NULL,
    CONSTRAINT PK_BBS PRIMARY KEY(BBS_NO)
);

--탈퇴
CREATE TABLE RETIRE_USERS (
	RETIRE_NO	NUMBER	NOT NULL,
	JOIN_DATE	DATE	NULL,
	RETIRE_DATE	DATE	NULL,
	ID	VARCHAR2(45 BYTE)	NULL
);

--휴면
CREATE TABLE SLEEP_USERS (
	SLEEP_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(45 BYTE)	NULL,
	PW	VARCHAR2(64 BYTE)	NULL,
	NAME	VARCHAR2(50 BYTE)	NULL,
	GENDER	VARCHAR2(2 BYTE)	NULL,
	EMAIL	VARCHAR2(45 BYTE)	NULL,
	MOBILE	VARCHAR2(11 BYTE)	NULL,
	BIRTHYEAR	VARCHAR2(4 BYTE)	NULL,
	BIRTHDAY	VARCHAR2(4 BYTE)	NULL,
	POSTCODE	VARCHAR2(5 BYTE)	NULL,
	ROAD_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	JIBUN_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	DETAIL_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	EXTRA_ADDRESS 	VARCHAR2(100 BYTE),  
	AGREE_CODE	NUMBER	NULL,
	SNS_TYPE	VARCHAR2(10 BYTE)	NULL,
	JOIN_DATE	DATE	NULL,
	PW_MODIFY_DATE	DATE	NULL,
	LAST_LOGIN_DATE	DATE	NULL,
	SLEEP_DATE 	DATE 	NULL,
	POINT		NUMBER	NULL
);

--업로드
CREATE TABLE UPLOAD (
	UPLOAD_NO	            NUMBER	            NOT NULL,
	ID	                    VARCHAR2(45 BYTE)	NOT NULL,
	UPLOAD_TITLE	            VARCHAR2(100 BYTE)	NOT NULL,
	UPLOAD_CONTENT	        VARCHAR2(100 BYTE)	NULL,
	UPLOAD_CREATE_DATE	    DATE	            NULL,
	UPLOAD_LAST_MODIFY_DATE	DATE	            NULL,
	UPLOAD_HIT	            NUMBER	            NULL,
	IP	                    VARCHAR2(30 BYTE)	NOT NULL
);

-- 다운로드
CREATE TABLE ATTACH (
	ATTACH_NO	            NUMBER	            NOT NULL,
	UPLOAD_NO	            NUMBER	            NOT NULL,
	ORIGIN	                VARCHAR2(300 BYTE)	NULL,
	FILESYSTEM	            VARCHAR2(40 BYTE)	NULL,
	DOWNLOAD_CNT	            NUMBER	            NULL,
	PATH	                VARCHAR2(300 BYTE)	NULL
);

--갤러리
CREATE TABLE GALLERY (
   GAL_NO                NUMBER,
   ID                    VARCHAR2(45 BYTE)    NOT NULL,
   GAL_TITLE            VARCHAR2(100 BYTE)	  NOT NULL,
   GAL_CONTENT            VARCHAR2(1000 BYTE) NOT NULL,
   GAL_CREATE_DATE     DATE,
   GAL_LAST_MODIFY_DATE DATE,
   GAL_HIT                NUMBER,
   LIKE_COUNT           NUMBER,
   IP                    VARCHAR2(30 BYTE) NOT NULL,
    CONSTRAINT PK_GALLERY PRIMARY KEY (GAL_NO)
);

--갤러리댓글
CREATE TABLE TBL_COMMENT (
   COMMENT_NO                NUMBER NOT NULL,
   GAL_NO                    NUMBER NOT NULL,
   ID                        VARCHAR2(45 BYTE)   NOT NULL,
   COMMENT_TITLE            VARCHAR2(100 BYTE) NOT NULL,
   COMMENT_CREATE_DATE        DATE,
   COMMNET_LAST_MODIFY_DATE DATE,
   IP                        VARCHAR2(30 BYTE) NOT NULL,
    CONSTRAINT PK_COMMENT PRIMARY KEY (COMMENT_NO)
);

--노트
CREATE TABLE SUMMERNOTE_IMAGE
(
    GAL_NO NUMBER,
    FILESYSTEM VARCHAR2(40 BYTE)
);

--좋아요
CREATE TABLE TBL_LIKE (
   LIKE_NO    NUMBER   NOT NULL,
   GAL_NO       NUMBER   NOT NULL,
   ID           VARCHAR2(45 BYTE)   NOT NULL,
   LIKE_DATE   DATE   NULL,
    CONSTRAINT PK_LIKE PRIMARY KEY (LIKE_NO)
);





-- 외래키

ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (
	USER_NO
);

ALTER TABLE ACCESS_LOG ADD CONSTRAINT FK_USERS_ACCESS_LOG FOREIGN KEY (ID) REFERENCES USERS (ID) ON DELETE CASCADE;



ALTER TABLE UPLOAD ADD CONSTRAINT PK_UPLOAD PRIMARY KEY(UPLOAD_NO);


ALTER TABLE ATTACH ADD CONSTRAINT PK_ATTACH PRIMARY KEY(ATTACH_NO);


ALTER TABLE UPLOAD ADD CONSTRAINT FK_UPLOAD_USERS FOREIGN KEY(ID)
    REFERENCES USERS(ID);
 
ALTER TABLE ATTACH ADD CONSTRAINT FK_ATTACH_USERS FOREIGN KEY(UPLOAD_NO)
    REFERENCES UPLOAD(UPLOAD_NO);

ALTER TABLE SUMMERNOTE_IMAGE
    ADD CONSTRAINT FK_SUMMERNOTE_GALLERY
        FOREIGN KEY(GAL_NO) REFERENCES GALLERY(GAL_NO)
            ON DELETE CASCADE;

ALTER TABLE SLEEP_USERS ADD CONSTRAINT PK_SLEEP_USERS PRIMARY KEY (
	SLEEP_NO
);

ALTER TABLE RETIRE_USERS ADD CONSTRAINT PK_RETIRE_USERS PRIMARY KEY (
	RETIRE_NO
);

ALTER TABLE GALLERY
    ADD CONSTRAINT FK_GALLERY_USERS
        FOREIGN KEY(ID) REFERENCES USERS(ID)
            ON DELETE CASCADE;

ALTER TABLE TBL_COMMENT
    ADD CONSTRAINT FK_COMMENT_GALLERY
        FOREIGN KEY(GAL_NO) REFERENCES GALLERY(GAL_NO)
            ON DELETE CASCADE;

ALTER TABLE TBL_COMMENT
    ADD CONSTRAINT FK_COMMENT_USERS
        FOREIGN KEY(ID) REFERENCES USERS(ID)
            ON DELETE CASCADE;

ALTER TABLE TBL_LIKE
    ADD CONSTRAINT FK_LIKE_GALLERY
        FOREIGN KEY(GAL_NO) REFERENCES GALLERY(GAL_NO)
            ON DELETE CASCADE;

ALTER TABLE TBL_LIKE
    ADD CONSTRAINT FK_LIKE_USERS
        FOREIGN KEY(ID) REFERENCES USERS(ID)
            ON DELETE CASCADE;

ALTER TABLE BBS
    ADD CONSTRAINT FK_BBS
        FOREIGN KEY(ID) REFERENCES USERS(ID)
            ON DELETE CASCADE;