DROP SEQUENCE SLEEP_USERS_SEQ;
CREATE SEQUENCE SLEEP_USERS_SEQ NOCACHE;


DROP TABLE SLEEP_USERS;

CREATE TABLE SLEEP_USERS (
	SLEEP_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(45 BYTE)	NULL,
	PW	VARCHAR2(64 BYTE)	NULL,
	NAME	VARCHAR2(50 BYTE)	NULL,
	GENDER	VARCHAR2(2 BYTE)	NULL,
	EMAIL	VARCHAR2(45 BYTE)	NULL,
	MOBILE	VARCHAR2(11 BYTE)	NULL,
	BIRTHYEAR	VARCHAR2(4 BYTE)	NULL,
	BIRTHDAY	VARCHAR2(4 BYTE)	NULL,
	POSTCODE	VARCHAR2(5 BYTE)	NULL,
	ROAD_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	JIBUN_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	DETAIL_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	EXTRA_ADDRESS 	VARCHAR2(100 BYTE),  
	AGREE_CODE	NUMBER	NULL,
	SNS_TYPE	VARCHAR2(10 BYTE)	NULL,
	JOIN_DATE	DATE	NULL,
	PW_MODIFY_DATE	DATE	NULL,
	LAST_LOGIN_DATE	DATE	NULL,
	SLEEP_DATE 	DATE 	NULL,
	POINT		NUMBER	NULL
);

ALTER TABLE SLEEP_USERS ADD CONSTRAINT PK_SLEEP_USERS PRIMARY KEY (
	SLEEP_NO
);