
DROP SEQUENCE USERS_SEQ;
CREATE SEQUENCE USERS_SEQ NOCACHE;



DROP TABLE USERS;
CREATE TABLE USERS (
	USER_NO	                NUMBER	            NOT NULL,
	ID	                    VARCHAR2(45 BYTE)	UNIQUE NOT NULL,
	PW	                    VARCHAR2(64 BYTE)	NOT NULL,
	NAME	                VARCHAR2(50 BYTE)	NOT NULL,
	GENDER	                VARCHAR2(2 BYTE)    NOT NULL,
	EMAIL	                VARCHAR2(50 BYTE)	NOT NULL,
	MOBILE	                VARCHAR2(11 BYTE)	NOT NULL,
	BIRTHYEAR	            VARCHAR2(4 BYTE)	NOT NULL,
	BIRTHDAY	            VARCHAR2(4 BYTE)	NOT NULL,
	POSTCODE                VARCHAR2(5 BYTE)	NULL,
	ROAD_ADDRESS	        VARCHAR2(100 BYTE)	NULL,
	JIBUN_ADDRESS	        VARCHAR2(100 BYTE)	NULL,
	DETAIL_ADDRESS	        VARCHAR2(100 BYTE)	NULL,
	EXTRA_ADDRESS	        VARCHAR2(100 BYTE)	NULL,
	AGREE_CODE	            NUMBER	            NOT NULL,
	SNS_TYPE	            VARCHAR2(10 BYTE)	NULL,
	JOIN_DATE	            DATE	            NOT NULL,
	PW_MODIFY_DATE	        DATE	            NULL,
	INFO_MODIFY_DATE        	DATE	            NULL,
	SESSION_ID	            VARCHAR2(32 BYTE)	NULL,
	SESSION_LIMIT_DATE      	DATE	            NULL,
	POINT	                NUMBER	            NULL
);

ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (
	USER_NO
);

-- admin/1111
INSERT INTO USERS VALUES(USERS_SEQ.NEXTVAL, 'admin', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '관리자', 'M', 'admin@home.com', '01011111111', '2000', '1111', NULL, NULL, NULL, NULL, NULL, 0, NULL, SYSDATE, SYSDATE, SYSDATE, NULL, NULL, 0);
COMMIT;